//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acmarkert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("acmarkert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAAzWD1XjY:APA91bF00qEhAlcdgb4lkdz4kqhWr-6Bu-VjriFxMBpMf0-5xpSsgVzLbPvQZScx8s-hAuqAgO5GmSJa_qtAfT1J8YRA3Dnx93VtmHs8YKylUXkTZtbra18EFYwW8t092D8_1dgzRE7W.
        /// </summary>
        internal static string API_FIREBASE {
            get {
                return ResourceManager.GetString("API_FIREBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string DEVELOP {
            get {
                return ResourceManager.GetString("DEVELOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms8xcezxkgaju3vdqiq2.
        /// </summary>
        internal static string ID_OPEN_PAY {
            get {
                return ResourceManager.GetString("ID_OPEN_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp5ytqjpfvw5u54vtitu.
        /// </summary>
        internal static string ID_OPEN_PAY_DEV {
            get {
                return ResourceManager.GetString("ID_OPEN_PAY_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pk_37124dcecfd649709367bc55258645d8.
        /// </summary>
        internal static string PK_OPEN_PAY {
            get {
                return ResourceManager.GetString("PK_OPEN_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pk_915dbec970954c9dba39596d80667083.
        /// </summary>
        internal static string PK_OPEN_PAY_DEV {
            get {
                return ResourceManager.GetString("PK_OPEN_PAY_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk_9c710592f110440e9d9f168a33fc7583.
        /// </summary>
        internal static string SK_OPEN_PAY {
            get {
                return ResourceManager.GetString("SK_OPEN_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk_1e137acb04004ee89113f5a57c8f9c44.
        /// </summary>
        internal static string SK_OPEN_PAY_DEV {
            get {
                return ResourceManager.GetString("SK_OPEN_PAY_DEV", resourceCulture);
            }
        }
    }
}
